#include <fstream>

using namespace std;

int main() {
	 ofstream cout("multiplication.out");
	cout << "start: s\n";
	cout << "accept: ac\n";
	cout << "reject: rj\n";
	cout << "blank: _\n";
	cout << "\n";
	cout << "s 0 -> l 0 <\n";
	cout << "s 1 -> l 1 <\n";
	cout << "\n";
	cout << "l _ -> z # <\n";
	cout << "\n";
	cout << "z _ -> f 0 >\n";
	cout << "\n";
	cout << "f 0 -> f 0 >\n";
	cout << "f 1 -> f 1 >\n";
	cout << "f * -> f * >\n";
	cout << "f # -> f # >\n";
	cout << "f _ -> m _ <\n";
	cout << "\n";
	cout << "m 1 -> r 0 <\n";
	cout << "m 0 -> r1 1 <\n";
	cout << "\n";
	cout << "r 0 -> r 0 <\n";
	cout << "r 1 -> r 1 <\n";
	cout << "\n";
	cout << "r1 1 -> r 0 <\n";
	cout << "r1 0 -> r1 1 <\n";
	cout << "r1 * -> fw * >\n";
	cout << "\n";
	cout << "fw 0 -> fw 0 >\n";
	cout << "fw 1 -> fw 1 >\n";
	cout << "fw _ -> cle _ <\n";
	cout << "\n";
	cout << "cle 0 -> cle _ <\n";
	cout << "cle 1 -> cle _ <\n";
	cout << "cle * -> cle _ <\n";
	cout << "cle # -> ret _ <\n";
	cout << "\n";
	cout << "ret 0 -> ret 0 <\n";
	cout << "ret 1 -> ret 1 < \n";
	cout << "ret _ -> ac _ > \n";
	cout << "\n";
	cout << "r * -> su * <\n";
	cout << "su 0' -> su 0' <\n";
	cout << "su 1' -> su 1' <\n";
	cout << "su 0 -> p0 0' <\n";
	cout << "su 1 -> p1 1' <\n";
	cout << "su # -> clr # <\n";
	cout << "\n";
	cout << "clr 0' -> clr 0 <\n";
	cout << "clr 1' -> clr 1 <\n";
	cout << "clr 0 -> fcl 0 >\n";
	cout << "clr 1 -> fcl 1 >\n";
	cout << "clr _ -> fcl _ >\n";
	cout << "\n";
	cout << "fcl 0' -> fcl 0 >\n";
	cout << "fcl 1' -> fcl 1 >\n";
	cout << "fcl 0 -> fcl 0 >\n";
	cout << "fcl 1 -> fcl 1 >\n";
	cout << "fcl # -> fcl # >\n";
	cout << "fcl * -> f * >\n";
	cout << "\n";
	cout << "p0 0 -> p0 0 <\n";
	cout << "p0 1 -> p0 1 <\n";
	cout << "p0 # -> p00 # <\n";
	cout << "\n";
	cout << "p00 0' -> p00 0' <\n";
	cout << "p00 1' -> p00 1' <\n";
	cout << "p00 0 -> fs 0' >\n";
	cout << "p00 1 -> fs 1' >\n";
	cout << "p00 _ -> fs 0' >\n";
	cout << "\n";
	cout << "p1 0 -> p1 0 <\n";
	cout << "p1 1 -> p1 1 <\n";
	cout << "p1 # -> p11 # <\n";
	cout << "\n";
	cout << "p11 0' -> p11 0' <\n";
	cout << "p11 1' -> p11 1' <\n";
	cout << "p11 0 -> fs 1' >\n";
	cout << "p11 _ -> fs 1' >\n";
	cout << "p11 1 -> p12 0' <\n";
	cout << "\n";
	cout << "p12 0 -> fs 1 >\n";
	cout << "p12 1 -> p12 0 <\n";
	cout << "p12 _ -> fs 1 >\n";
	cout << "\n";
	cout << "fs 0 -> fs 0 >\n";
	cout << "fs 1 -> fs 1 >\n";
	cout << "fs 0' -> fs 0' >\n";
	cout << "fs 1' -> fs 1' >\n";
	cout << "fs # -> fs # >\n";
	cout << "fs * -> su * <\n";
	cout << "\n";
	cout << "\n";
	cout << "\n";
	 cout.close();
}