#include <fstream>

using namespace std;

int main() {
	 ofstream cout("tandem.out");
	cout << "start: s\n";
	cout << "accept: ac\n";
	cout << "reject: rj \n";
	cout << "blank: _\n";
	cout << "\n";
	cout << "s 0 -> f 0' > \n";
	cout << "s 1 -> f 1' >\n";
	cout << "s 0'' -> ch 0'' <\n";
	cout << "s 1'' -> ch 1'' <\n";
	cout << "\n";
	cout << "ch 0' -> ch0 0 >\n";
	cout << "\n";
	cout << "ch0 0 -> ch0 0 >\n";
	cout << "ch0 1 -> ch0 1 >\n";
	cout << "ch0 0'' -> ch0 0'' >\n";
	cout << "ch0 1'' -> ch0 1'' >\n";
	cout << "ch0 _ -> ch00 _ <\n";
	cout << "\n";
	cout << "ch00 0 -> rj _ ^\n";
	cout << "ch00 1 -> rj _ ^\n";
	cout << "ch00 1'' -> rj _ ^\n";
	cout << "ch00 0'' -> rch _ <\n";
	cout << "\n";
	cout << "ch 1' -> ch1 1 >\n";
	cout << "ch1 0 -> ch1 0 >\n";
	cout << "ch1 1 -> ch1 1 >\n";
	cout << "ch1 0'' -> ch1 0'' >\n";
	cout << "ch1 1'' -> ch1 1'' >\n";
	cout << "ch1 _ -> ch11 _ <\n";
	cout << "\n";
	cout << "ch11 0 -> rj _ ^\n";
	cout << "ch11 1 -> rj _ ^\n";
	cout << "ch11 0'' -> rj _ ^\n";
	cout << "ch11 1'' -> rch _ <\n";
	cout << "\n";
	cout << "rch 0 -> rch 0 <\n";
	cout << "rch 1 -> rch 1 <\n";
	cout << "rch 0' -> ch 0' ^\n";
	cout << "rch 1' -> ch 1' ^\n";
	cout << "rch 0'' -> rch 0'' <\n";
	cout << "rch 1'' -> rch 1'' <\n";
	cout << "rch _ -> finalch _ >\n";
	cout << "\n";
	cout << "finalch 0 -> finalch 0 >\n";
	cout << "finalch 1 -> finalch 1 >\n";
	cout << "finalch 0'' -> rj _ ^\n";
	cout << "finalch 1'' -> rj _ ^\n";
	cout << "finalch _ -> ac _ ^\n";
	cout << "\n";
	cout << "f 0 -> f 0 >\n";
	cout << "f 1 -> f 1 >\n";
	cout << "f 0'' -> mark2 0'' <\n";
	cout << "f 1'' -> mark2 1'' <\n";
	cout << "f _ -> mark2 _ <\n";
	cout << "\n";
	cout << "mark2 0 -> r 0'' <\n";
	cout << "mark2 1 -> r 1'' <\n";
	cout << "mark2 1' -> rj _ ^\n";
	cout << "mark2 0' -> rj _ ^\n";
	cout << "\n";
	cout << "r 0 -> r 0 <\n";
	cout << "r 1 -> r 1 <\n";
	cout << "r 0' -> s 0' >\n";
	cout << "r 1' -> s 1' >\n";
	cout << "r 0'' -> r 0'' <\n";
	cout << "r 1'' -> r 1'' <\n";
	cout << "\n";
	 cout.close();
}