#include <fstream>

using namespace std;

int main() {
	 ofstream cout("infixlogic.out");
	cout << "1\n";
	cout << "\n";
	cout << "S ( -> f ( >\n";
	cout << "S 0 -> f 0 >\n";
	cout << "S 1 -> f 1 >\n";
	cout << "\n";
	cout << "f ( -> f ( >\n";
	cout << "f o -> f o >\n";
	cout << "f a -> f a >\n";
	cout << "f 0 -> f 0 >\n";
	cout << "f 1 -> f 1 >\n";
	cout << "f * -> f * >\n";
	cout << "f ) -> ca ) <\n";
	cout << "f _ -> ca _ <\n";
	cout << "\n";
	cout << "fo * -> fo * >\n";
	cout << "fo 0 -> fo 0 >\n";
	cout << "fo 1 -> fo 1 >\n";
	cout << "fo o -> fo o >\n";
	cout << "fo ) -> co * <\n";
	cout << "fo _ -> co _ <\n";
	cout << "\n";
	cout << "sk * -> sk * >\n";
	cout << "sk 0 -> sk 0 >\n";
	cout << "sk 1 -> sk 1 >\n";
	cout << "sk _ -> cl _ <\n";
	cout << "\n";
	cout << "cl * -> cl _ <\n";
	cout << "cl 0 -> rcl0 _ <\n";
	cout << "cl 1 -> rcl1 _ <\n";
	cout << "\n";
	cout << "rcl0 * -> rcl0 _ <\n";
	cout << "rcl1 * -> rcl1 _ <\n";
	cout << "rcl0 _ -> AC 0 ^\n";
	cout << "rcl1 _ -> AC 1 ^\n";
	cout << "\n";
	cout << "ca * -> ca * <\n";
	cout << "ca 0 -> ca 0 <\n";
	cout << "ca 1 -> ca 1 <\n";
	cout << "ca o -> ca o <\n";
	cout << "ca ( -> fo ( >\n";
	cout << "ca _ -> fo _ >\n";
	cout << "ca a -> fa0 a >\n";
	cout << "fa0 * -> fa0 * >\n";
	cout << "fa0 0 -> fa00 * <\n";
	cout << "fa0 1 -> fa01 * <\n";
	cout << "fa00 * -> fa00 * <\n";
	cout << "fa00 a -> fa00 * <\n";
	cout << "fa00 0 -> ca 0 <\n";
	cout << "fa00 1 -> ca 0 <\n";
	cout << "fa01 * -> fa01 * <\n";
	cout << "fa01 a -> fa01 * <\n";
	cout << "fa01 0 -> ca 0 <\n";
	cout << "fa01 1 -> ca 1 <\n";
	cout << "\n";
	cout << "co * -> co * <\n";
	cout << "co 0 -> co 0 <\n";
	cout << "co 1 -> co 1 <\n";
	cout << "co ( -> f * >\n";
	cout << "co o -> fo0 o >\n";
	cout << "co _ -> sk _ >\n";
	cout << "fo0 * -> fo0 * >\n";
	cout << "fo0 0 -> fo00 * <\n";
	cout << "fo0 1 -> fo01 * <\n";
	cout << "fo00 * -> fo00 * <\n";
	cout << "fo00 o -> fo00 * <\n";
	cout << "fo00 0 -> co 0 <\n";
	cout << "fo00 1 -> co 1 <\n";
	cout << "fo01 * -> fo01 * <\n";
	cout << "fo01 o -> fo01 * <\n";
	cout << "fo01 0 -> co 1 <\n";
	cout << "fo01 1 -> co 1 <\n";
	cout << "\n";
	cout << "\n";
	 cout.close();
}